- name: install nginx
  hosts: localhost

  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
      become: true
    - name: Deploy NGINX config
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: Restart NGINX
      become: true

    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
      become: true

    - name: Ensure NGINX is running
      service:
        name: nginx
        state: started
        enabled: true
      become: true
