- name: Install nginx
  ansible.builtin.package:
    name: nginx
    state: present
  become: true
- name: Create a certifcate directory
  file:
    path: /etc/nginx/certs
    state: directory
    mode: "0655"
  become: yes

- name: Generate self-signed SSL certificate if not exists
  ansible.builtin.command: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048   
    -keyout {{ ssl_key_path }}
    -out {{ ssl_cert_path }}   
    -subj "/CN=localhost"
  args:
    creates: "{{ ssl_cert_path }}"
  become: yes

- name: Deploy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart NGINX
  become: true

- name: Copy index file
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: Ensure nginx is running
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
  become: true
